[package]
name = "QuokkaPouch"
version = "0.1.0"
edition = "2024"

[dependencies]
wallet = { path = "wallet"}
subxt = "0.43.0"
bip39 = { version = "2.2.0", features = ["std"] }
hex = "0.4.3"
base64 = "0.22.1"
